version: "3.7"
services:
  php:
    build:
      args:
        user: a
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: php82-dto
    container_name: php82-dto
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
