version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
