version: "3.7"
services:
  app:
    image: antonphp/php82-composer-xdebug:v1.0.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - XDEBUG_SESSION=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./../:/var/www
      - ./ini/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./ini/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./ini/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - default

networks:
  default:
    name: ${CONTAINER_NAME}
