version: "3.7"
services:
  app:
    image: antonphp/php82-composer-xdebug:v1.0.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
      XDEBUG_CONFIG: "ide_key=${XDEBUG_IDE_KEY} client_host=${XDEBUG_CLIENT_HOST} start_with_request=${XDEBUG_START_WITH_REQUEST}"
    volumes:
      - ./../:/var/www
      - ./ini/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./ini/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./ini/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./../tests/_output:/opt/phpstorm-coverage/
    networks:
      - default

networks:
  default:
    name: ${CONTAINER_NAME}
